name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'

    - name: Install dependencies
      run: |
        cd flutter_project
        flutter pub get

    - name: Analyze
      run: |
        cd flutter_project
        flutter analyze

    - name: Run tests
      run: |
        cd flutter_project
        flutter test

    - name: Build Android AAB
      if: github.ref == 'refs/heads/main'
      run: |
        cd flutter_project
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
